version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/severstal
    depends_on:
      - migrations
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  migrations:
    build: .
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/severstal
    depends_on:
      - db
    volumes:
      - .:/app
    command: alembic upgrade head

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=severstal
    ports:
      - "5432:5432"

volumes:
  postgres_data: 