"""add_new_column

Revision ID: a28614ab4514
Revises: 001
Create Date: 2025-03-14 01:19:12.063510

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a28614ab4514"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "coils", sa.Column("updated_at", sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("coils", "updated_at")
    # ### end Alembic commands ###
